//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ventuz.Extention.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ventuz.Extention.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;AVConfig xmlns=&quot;http://www.ventuz.com/AVConfigFile/1.0/&quot;&gt;
        ///  &lt;Global&gt;
        ///    &lt;OutputFrameRate&gt;None&lt;/OutputFrameRate&gt;
        ///    &lt;SoftwareWatchdogTimeout&gt;0&lt;/SoftwareWatchdogTimeout&gt;
        ///    &lt;LogVideoEngineState&gt;false&lt;/LogVideoEngineState&gt;
        ///    &lt;ProductName&gt;Ventuz Runtime&lt;/ProductName&gt;
        ///    &lt;ProductVersion&gt;6.3.3.266&lt;/ProductVersion&gt;
        ///    &lt;ProductSerial&gt;&lt;/ProductSerial&gt;
        ///    &lt;ProjectName&gt;&lt;/ProjectName&gt;
        ///  &lt;/Global&gt;
        ///  &lt;Stream ID=&quot;DX_0&quot;&gt;
        ///    &lt;StartInError&gt;false&lt;/StartInError&gt;
        ///    &lt;Multisampling&gt;Best&lt;/Multisampling&gt;
        ///   [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string InitAVSetup {
            get {
                return ResourceManager.GetString("InitAVSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;RenderSetup xmlns=&quot;http://www.ventuz.com/RenderSetup/1.0/&quot;&gt;
        ///  &lt;Rects ID=&quot;&quot; Name=&quot;CLUSTER&quot; Rect=&quot;0, 0, 5678, 8765&quot; Origin=&quot;0, 0&quot; Color=&quot;0, 0, 0&quot; GUID=&quot;f2e62f31-a833-4785-8ac7-646384c809dc&quot; xmlns=&quot;http://www.ventuz.com/RenderSetupEditor/1.0/&quot;&gt;
        ///    &lt;Rects ID=&quot;1&quot; Name=&quot;M01&quot; Rect=&quot;0, 0, 5678, 8765&quot; Origin=&quot;0, 0&quot; Color=&quot;0, 0, 0&quot; GUID=&quot;86e1844b-3b4c-4b05-a4d9-5194fcf4dea1&quot;&gt;
        ///      &lt;Rects ID=&quot;1.1&quot; Name=&quot;M01.1&quot; Rect=&quot;0, 0, 5678, 8765&quot; Origin=&quot;0, 0&quot; Color=&quot;1, 0, 0&quot; GUID=&quot;5559cc6e-2225-419a-9f3d-0566b8ae4126&quot; /&gt;
        ///  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string InitRenderSetup {
            get {
                return ResourceManager.GetString("InitRenderSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Ventuz6_Designer {
            get {
                object obj = ResourceManager.GetObject("Ventuz6_Designer", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
